[mypy]
mypy_path = .
explicit_package_bases = True
check_untyped_defs = True
ignore_missing_imports = True
exclude = admin/templates

[mypy-socketio.*]
ignore_missing_imports = True

[tool.mypy]
ignore_missing_imports = True

