import pytest
from unittest.mock import AsyncMock, MagicMock, patch, call
from sqlalchemy.ext.asyncio import AsyncSession
from src.modules.balances.services import BalancesService
from src.modules.balances.schemas import RQUpdateBalance, RSBalance
from src.modules.balances.models import Balance
from src.domain.services.balances_recursive import _update_children_recursively
from src.modules.balances.decorators.models import BalanceDecorator
from core.database.models_registry import import_models

import_models()

class TestBalancesReactiveUpdate:
    @pytest.fixture
    def service(self):
        return BalancesService()

    @pytest.fixture
    def mock_db(self):
        return MagicMock(spec=AsyncSession)

    @pytest.mark.asyncio
    async def test_update_balance_triggers_hook(self, service, mock_db):
        """
        Verify that BalancesService.update_balance successfully updates
        the balance and returns the RSBalance, which would trigger the hook.
        """
        data = RQUpdateBalance(quantity=100.0)
        
        # Mock finding the balance
        mock_balance = Balance(id=1, type="basic", quantity=50.0, ref_value=1)
        mock_result = MagicMock()
        mock_result.scalar_one_or_none.return_value = mock_balance
        mock_db.execute = AsyncMock(return_value=mock_result)
        
        # We need an id for the mocked balance to pass pydantic validation if it needs uid
        # Assuming UID is generated by DB or default, let's just patch model_validate
        with patch('src.modules.balances.services.RSBalance.model_validate') as mock_validate:
            mock_rs = RSBalance(uid="abc", id=1, type="basic", quantity=100.0, ref_value=1)
            mock_validate.return_value = mock_rs
            
            result, error = await service.update_balance(id=1, balance_data=data, db=mock_db)
            
            assert error is None
            assert result.quantity == 100.0
            assert mock_balance.quantity == 100.0
            mock_db.commit.assert_called_once()
            mock_db.refresh.assert_called_once_with(mock_balance)

    @pytest.mark.asyncio
    async def test_recursive_update_reactive_flow(self, mock_db):
        """
        Test that updating a base balance propagates to reactive children.
        """
        parent_id = 1
        child_id = 2

        # 1. Find decorators: Returns a decorator pointing to child_id
        mock_decorator = BalanceDecorator(ref_balance_from=parent_id, ref_balance_to=child_id, is_reactive=True)
        
        # 2. Find parents of child_id: Returns the parent balance with new quantity
        mock_parent_balance = Balance(id=parent_id, quantity=100.0)
        
        # 3. Find child balance: Returns the child balance to be updated
        mock_child_balance = Balance(id=child_id, quantity=50.0)

        # We will mock db.execute to return these in sequence based on the query pattern
        # This is a bit brittle but standard for unit testing SQLAlchemy without a real DB
        call_count = 0
        def side_effect(*args, **kwargs):
            nonlocal call_count
            call_count += 1
            mock_res = MagicMock()
            if call_count == 1:
                # First query: select(BalanceDecorator)
                mock_res.scalars().all.return_value = [mock_decorator]
            elif call_count == 2:
                # Second query: select(Balance).join(...)
                mock_res.scalars().all.return_value = [mock_parent_balance]
            elif call_count == 3:
                # Third query: select(Balance).where(id=child)
                mock_res.scalar_one.return_value = mock_child_balance
            elif call_count == 4:
                # Fourth query: the recursive call for the child's children
                # return empty to break recursion
                mock_res.scalars().all.return_value = []
            return mock_res

        mock_db.execute = AsyncMock(side_effect=side_effect)

        await _update_children_recursively(parent_id, mock_db)

        # Verify child was updated to sum of parents (100.0)
        assert mock_child_balance.quantity == 100.0

    @pytest.mark.asyncio
    async def test_recursive_update_non_reactive_reverse_scenario(self, mock_db):
        """
        Test the reverse scenario: if is_reactive=False, it should NOT propagate.
        Actually, the initial query filters for is_reactive=True, so it should return []
        and do nothing.
        """
        parent_id = 1
        
        mock_res = MagicMock()
        mock_res.scalars().all.return_value = [] # No reactive decorators
        mock_db.execute = AsyncMock(return_value=mock_res)

        await _update_children_recursively(parent_id, mock_db)

        # Execute should only be called once to find decorators, and stop there.
        assert mock_db.execute.call_count == 1
