"""Refactor remaining pivot tables to RelationBaseAsync

Revision ID: 15a28bdc8b2e
Revises: 78e7a0e4063a
Create Date: 2026-05-07 19:18:36.265490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15a28bdc8b2e'
down_revision: Union[str, None] = '78e7a0e4063a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_entities_hierarchy',
    sa.Column('ref_entity_top', sa.Integer(), nullable=False),
    sa.Column('ref_entity_bottom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_entity_bottom'], ['business_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_entity_top'], ['business_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ref_entity_top', 'ref_entity_bottom')
    )
    op.create_table('invoice_business_entities',
    sa.Column('ref_invoice', sa.Integer(), nullable=False),
    sa.Column('ref_business_entity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('ref_invoice', 'ref_business_entity')
    )
    op.create_table('meta_business_entities',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_business_entity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'ref_business_entity')
    )
    op.create_index('idx_values_meta_ref_business_entity', 'meta_business_entities', ['key', 'ref_business_entity'], unique=True)
    op.create_table('meta_invoices',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_invoice', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('key', 'ref_invoice')
    )
    op.create_index('idx_meta_invoices_key_ref', 'meta_invoices', ['key', 'ref_invoice'], unique=True)
    op.create_table('meta_permissions',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_permission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_permission'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('key', 'ref_permission')
    )
    op.create_index('idx_meta_permissions_key_ref_permission', 'meta_permissions', ['key', 'ref_permission'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('meta_persons',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_person', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_person'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('key', 'ref_person')
    )
    op.create_index('idx_values_meta_ref_person', 'meta_persons', ['key', 'ref_person'], unique=True)
    op.create_table('meta_users',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key', 'ref_user')
    )
    op.create_index('idx_meta_users_key_ref_user', 'meta_users', ['key', 'ref_user'], unique=True)
    op.create_table('meta_values',
    sa.Column('ref_value', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ref_value'], ['values.id'], ),
    sa.PrimaryKeyConstraint('ref_value', 'key')
    )
    op.create_index('idx_values_meta_key_ref_value', 'meta_values', ['key', 'ref_value'], unique=True)
    op.create_table('values_hierarchy',
    sa.Column('ref_value_top', sa.Integer(), nullable=False),
    sa.Column('ref_value_bottom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_value_bottom'], ['values.id'], ),
    sa.ForeignKeyConstraint(['ref_value_top'], ['values.id'], ),
    sa.PrimaryKeyConstraint('ref_value_top', 'ref_value_bottom')
    )
    op.create_table('balances_business_entities',
    sa.Column('ref_business_entity', sa.Integer(), nullable=False),
    sa.Column('ref_balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_balance'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ref_business_entity', 'ref_balance')
    )
    op.create_table('meta_comparison_values',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_comparison_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_comparison_value'], ['comparation_values.id'], ),
    sa.PrimaryKeyConstraint('key', 'ref_comparison_value')
    )
    op.create_index('idx_values_meta_ref_comparison_value', 'meta_comparison_values', ['key', 'ref_comparison_value'], unique=True)
    op.create_table('invoice_transactions',
    sa.Column('ref_invoice', sa.Integer(), nullable=False),
    sa.Column('ref_transaction', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['ref_transaction'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('ref_invoice', 'ref_transaction')
    )
    op.create_table('meta_comparison_values_historical',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_comparison_value_historical', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_comparison_value_historical'], ['comparation_values_historical.id'], ),
    sa.PrimaryKeyConstraint('key', 'ref_comparison_value_historical')
    )
    op.create_index('idx_meta_comp_val_hist_ref_comp_val_hist', 'meta_comparison_values_historical', ['key', 'ref_comparison_value_historical'], unique=True)
    op.create_table('meta_transactions',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_transaction', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_transaction'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('key', 'ref_transaction')
    )
    op.create_index('idx_values_meta_key_ref_transaction', 'meta_transactions', ['key', 'ref_transaction'], unique=True)
    op.create_table('meta_transactions_buffer',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_transaction_buffer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_transaction_buffer'], ['transactions_buffer.id'], ),
    sa.PrimaryKeyConstraint('key', 'ref_transaction_buffer')
    )
    op.create_index('idx_meta_tx_buffer_key_ref', 'meta_transactions_buffer', ['key', 'ref_transaction_buffer'], unique=True)
    op.drop_index('idx_balances_active', table_name='balances', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_active', table_name='business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_groups_active', table_name='business_entities_groups', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_groups_connections_active', table_name='business_entities_groups_connections', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_business_entities_groups_connections_id', table_name='business_entities_groups_connections')
    op.drop_index('ix_business_entities_groups_connections_uid', table_name='business_entities_groups_connections')
    op.drop_column('business_entities_groups_connections', 'id')
    op.execute("DROP POLICY IF EXISTS business_entities_groups_connections_active_policy ON business_entities_groups_connections;")
    op.drop_column('business_entities_groups_connections', 'deleted_at')
    op.drop_column('business_entities_groups_connections', 'updated_at')
    op.drop_column('business_entities_groups_connections', 'is_deleted')
    op.drop_column('business_entities_groups_connections', 'created_at')
    op.drop_column('business_entities_groups_connections', 'uid')
    op.drop_index('idx_comparation_values_active', table_name='comparation_values', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_comparation_values_historical_active', table_name='comparation_values_historical', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_image_files_active', table_name='image_files', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_invoices_active', table_name='invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_options_active', table_name='options', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_permissions_active', table_name='permissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_persons_active', table_name='persons', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_roles_active', table_name='roles', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_transactions_active', table_name='transactions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_transactions_buffer_active', table_name='transactions_buffer', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_users_active', table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english', username || ' ' || email || ' ' || full_name)")], unique=False, postgresql_using='gin')
    op.drop_index('idx_values_active', table_name='values', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_values_active', 'values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english'::regconfig, (((username::text || ' '::text) || email::text) || ' '::text) || full_name::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_users_active', 'users', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_transactions_buffer_active', 'transactions_buffer', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_transactions_active', 'transactions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_roles_active', 'roles', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_persons_active', 'persons', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_permissions_active', 'permissions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_options_active', 'options', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_invoices_active', 'invoices', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_image_files_active', 'image_files', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_comparation_values_historical_active', 'comparation_values_historical', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_comparation_values_active', 'comparation_values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.add_column('business_entities_groups_connections', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('business_entities_groups_connections', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('business_entities_groups_connections', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('business_entities_groups_connections', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('business_entities_groups_connections', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('business_entities_groups_connections', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_business_entities_groups_connections_uid', 'business_entities_groups_connections', ['uid'], unique=True)
    op.create_index('ix_business_entities_groups_connections_id', 'business_entities_groups_connections', ['id'], unique=True)
    op.create_index('idx_business_entities_groups_connections_active', 'business_entities_groups_connections', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_groups_active', 'business_entities_groups', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_active', 'business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_balances_active', 'balances', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_tx_buffer_key_ref', table_name='meta_transactions_buffer')
    op.drop_table('meta_transactions_buffer')
    op.drop_index('idx_values_meta_key_ref_transaction', table_name='meta_transactions')
    op.drop_table('meta_transactions')
    op.drop_index('idx_meta_comp_val_hist_ref_comp_val_hist', table_name='meta_comparison_values_historical')
    op.drop_table('meta_comparison_values_historical')
    op.drop_table('invoice_transactions')
    op.drop_index('idx_values_meta_ref_comparison_value', table_name='meta_comparison_values')
    op.drop_table('meta_comparison_values')
    op.drop_table('balances_business_entities')
    op.drop_table('values_hierarchy')
    op.drop_index('idx_values_meta_key_ref_value', table_name='meta_values')
    op.drop_table('meta_values')
    op.drop_index('idx_meta_users_key_ref_user', table_name='meta_users')
    op.drop_table('meta_users')
    op.drop_index('idx_values_meta_ref_person', table_name='meta_persons')
    op.drop_table('meta_persons')
    op.drop_table('role_permissions')
    op.drop_index('idx_meta_permissions_key_ref_permission', table_name='meta_permissions')
    op.drop_table('meta_permissions')
    op.drop_index('idx_meta_invoices_key_ref', table_name='meta_invoices')
    op.drop_table('meta_invoices')
    op.drop_index('idx_values_meta_ref_business_entity', table_name='meta_business_entities')
    op.drop_table('meta_business_entities')
    op.drop_table('invoice_business_entities')
    op.drop_table('business_entities_hierarchy')
    # ### end Alembic commands ###
