"""optimize_indexes

Revision ID: 305d9cbda18c
Revises: 5f89fc039631
Create Date: 2026-04-18 21:50:22.595804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305d9cbda18c'
down_revision: Union[str, None] = '5f89fc039631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_balances_active', table_name='balances', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_balances_ref_value_active', 'balances', ['ref_value'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_balances_type_active', 'balances', ['type'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_balances_business_entities_active', table_name='balances_business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_active', table_name='business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_groups_active', table_name='business_entities_groups', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_groups_connections_active', table_name='business_entities_groups_connections', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_hierarchy_active', table_name='business_entities_hierarchy', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_comparation_values_active', table_name='comparation_values', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_comparation_values_value_from_active', 'comparation_values', ['value_from'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_comparation_values_value_to_active', 'comparation_values', ['value_to'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_comparation_values_historical_active', table_name='comparation_values_historical', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_image_files_active', table_name='image_files', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_invoice_business_entities_active', table_name='invoice_business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_invoice_transactions_active', table_name='invoice_transactions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_invoices_active', table_name='invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_business_entities_active', table_name='meta_business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_comparison_values_active', table_name='meta_comparison_values', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_comparison_values_historical_active', table_name='meta_comparison_values_historical', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_invoices_active', table_name='meta_invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_permissions_active', table_name='meta_permissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_persons_active', table_name='meta_persons', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_transactions_active', table_name='meta_transactions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_transactions_buffer_active', table_name='meta_transactions_buffer', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_users_active', table_name='meta_users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_values_active', table_name='meta_values', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_options_active', table_name='options', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_permissions_active', table_name='permissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_persons_active', table_name='persons', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_role_permissions_active', table_name='role_permissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_roles_active', table_name='roles', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_transactions_active', table_name='transactions', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_transactions_ref_balance_from_active', 'transactions', ['ref_balance_from'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_ref_balance_to_active', 'transactions', ['ref_balance_to'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_ref_by_user_active', 'transactions', ['ref_by_user'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_reference_code_active', 'transactions', ['reference_code'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_transactions_buffer_active', table_name='transactions_buffer', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_transactions_buffer_ref_balance_from_active', 'transactions_buffer', ['ref_balance_from'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_buffer_ref_balance_to_active', 'transactions_buffer', ['ref_balance_to'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_buffer_ref_by_user_active', 'transactions_buffer', ['ref_by_user'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_buffer_state_active', 'transactions_buffer', ['state'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_active', table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english', username || ' ' || email || ' ' || full_name)")], unique=False, postgresql_using='gin')
    op.create_index('ix_users_role_ref_active', 'users', ['role_ref'], unique=False, postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_values_active', table_name='values', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_values_context_active', 'values', ['context'], unique=False)
    op.drop_index('idx_values_hierarchy_active', table_name='values_hierarchy', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_values_hierarchy_active', 'values_hierarchy', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_values_context_active', table_name='values')
    op.create_index('idx_values_active', 'values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_users_role_ref_active', table_name='users', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english'::regconfig, (((username::text || ' '::text) || email::text) || ' '::text) || full_name::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_users_active', 'users', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_transactions_buffer_state_active', table_name='transactions_buffer', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_buffer_ref_by_user_active', table_name='transactions_buffer', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_buffer_ref_balance_to_active', table_name='transactions_buffer', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_buffer_ref_balance_from_active', table_name='transactions_buffer', postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_transactions_buffer_active', 'transactions_buffer', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_transactions_reference_code_active', table_name='transactions', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_ref_by_user_active', table_name='transactions', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_ref_balance_to_active', table_name='transactions', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_ref_balance_from_active', table_name='transactions', postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_transactions_active', 'transactions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_roles_active', 'roles', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_role_permissions_active', 'role_permissions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_persons_active', 'persons', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_permissions_active', 'permissions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_options_active', 'options', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_values_active', 'meta_values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_users_active', 'meta_users', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_transactions_buffer_active', 'meta_transactions_buffer', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_transactions_active', 'meta_transactions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_persons_active', 'meta_persons', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_permissions_active', 'meta_permissions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_invoices_active', 'meta_invoices', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_comparison_values_historical_active', 'meta_comparison_values_historical', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_comparison_values_active', 'meta_comparison_values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_business_entities_active', 'meta_business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_invoices_active', 'invoices', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_invoice_transactions_active', 'invoice_transactions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_invoice_business_entities_active', 'invoice_business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_image_files_active', 'image_files', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_comparation_values_historical_active', 'comparation_values_historical', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_comparation_values_value_to_active', table_name='comparation_values', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_comparation_values_value_from_active', table_name='comparation_values', postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_comparation_values_active', 'comparation_values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_hierarchy_active', 'business_entities_hierarchy', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_groups_connections_active', 'business_entities_groups_connections', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_groups_active', 'business_entities_groups', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_active', 'business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_balances_business_entities_active', 'balances_business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_balances_type_active', table_name='balances', postgres_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_balances_ref_value_active', table_name='balances', postgres_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_balances_active', 'balances', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
