"""initial_reconstruction

Revision ID: 38e388bb1ffa
Revises: 
Create Date: 2026-04-24 19:33:31.315084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e388bb1ffa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_entities',
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_business_entities_id'), 'business_entities', ['id'], unique=True)
    op.create_index(op.f('ix_business_entities_uid'), 'business_entities', ['uid'], unique=True)
    op.create_table('business_entities_groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_business_entities_groups_id'), 'business_entities_groups', ['id'], unique=True)
    op.create_index(op.f('ix_business_entities_groups_uid'), 'business_entities_groups', ['uid'], unique=True)
    op.create_table('image_files',
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id_file', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_image_files_id'), 'image_files', ['id'], unique=True)
    op.create_index(op.f('ix_image_files_uid'), 'image_files', ['uid'], unique=True)
    op.create_table('invoices',
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=True)
    op.create_index(op.f('ix_invoices_uid'), 'invoices', ['uid'], unique=True)
    op.create_table('options',
    sa.Column('context', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'id'),
    sa.UniqueConstraint('context', 'name', name='uq_options_context_name')
    )
    op.create_index('idx_options_context', 'options', ['context'], unique=False)
    op.create_index('idx_options_name', 'options', ['name'], unique=False)
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=True)
    op.create_index(op.f('ix_options_uid'), 'options', ['uid'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=True)
    op.create_index(op.f('ix_permissions_uid'), 'permissions', ['uid'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'id'),
    sa.UniqueConstraint('level')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=True)
    op.create_index(op.f('ix_roles_uid'), 'roles', ['uid'], unique=True)
    op.create_table('values',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('context', sa.String(length=100), nullable=False),
    sa.Column('expression', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'id'),
    sa.UniqueConstraint('name', 'context', 'type', name='uix_values_name_context_type')
    )
    op.create_index('ix_values_context_active', 'values', ['context'], unique=False)
    op.create_index(op.f('ix_values_id'), 'values', ['id'], unique=True)
    op.create_index('ix_values_name_context', 'values', ['name', 'context'], unique=False)
    op.create_index('ix_values_name_context_type', 'values', ['name', 'context', 'type'], unique=False)
    op.create_index('ix_values_name_type', 'values', ['name', 'type'], unique=False)
    op.create_index(op.f('ix_values_uid'), 'values', ['uid'], unique=True)
    op.create_table('balances',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('ref_value', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_value'], ['values.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_balances_id'), 'balances', ['id'], unique=True)
    op.create_index('ix_balances_ref_value_active', 'balances', ['ref_value'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_balances_type_active', 'balances', ['type'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_balances_uid'), 'balances', ['uid'], unique=True)
    op.create_table('business_entities_groups_connections',
    sa.Column('ref_business_entities_group', sa.Integer(), nullable=False),
    sa.Column('ref_business_entities', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_business_entities'], ['business_entities.id'], ),
    sa.ForeignKeyConstraint(['ref_business_entities_group'], ['business_entities_groups.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id'),
    sa.UniqueConstraint('ref_business_entities_group', 'ref_business_entities', name='uq_business_entities_groups_connections')
    )
    op.create_index(op.f('ix_business_entities_groups_connections_id'), 'business_entities_groups_connections', ['id'], unique=True)
    op.create_index(op.f('ix_business_entities_groups_connections_uid'), 'business_entities_groups_connections', ['uid'], unique=True)
    op.create_table('business_entities_hierarchy',
    sa.Column('ref_entity_top', sa.Integer(), nullable=False),
    sa.Column('ref_entity_bottom', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_entity_bottom'], ['business_entities.id'], ),
    sa.ForeignKeyConstraint(['ref_entity_top'], ['business_entities.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_business_entities_hierarchy_id'), 'business_entities_hierarchy', ['id'], unique=True)
    op.create_index(op.f('ix_business_entities_hierarchy_uid'), 'business_entities_hierarchy', ['uid'], unique=True)
    op.create_table('comparation_values',
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('quantity_from', sa.Integer(), nullable=False),
    sa.Column('quantity_to', sa.Float(), nullable=False),
    sa.Column('value_from', sa.Integer(), nullable=False),
    sa.Column('value_to', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['value_from'], ['values.id'], ),
    sa.ForeignKeyConstraint(['value_to'], ['values.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id'),
    sa.UniqueConstraint('value_from', 'value_to', 'context', name='uix_comparison_values_value_from_value_to')
    )
    op.create_index('ix_comparation_values_context_active', 'comparation_values', ['context'], unique=False)
    op.create_index(op.f('ix_comparation_values_id'), 'comparation_values', ['id'], unique=True)
    op.create_index(op.f('ix_comparation_values_uid'), 'comparation_values', ['uid'], unique=True)
    op.create_index('ix_comparation_values_value_from_active', 'comparation_values', ['value_from'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_comparation_values_value_to_active', 'comparation_values', ['value_to'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_comparison_values_value_from_context', 'comparation_values', ['value_from', 'context'], unique=False)
    op.create_index('ix_comparison_values_value_to_context', 'comparation_values', ['value_to', 'context'], unique=False)
    op.create_table('invoice_business_entities',
    sa.Column('ref_invoice', sa.Integer(), nullable=False),
    sa.Column('ref_business_entity', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], ),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_invoice_business_entities_id'), 'invoice_business_entities', ['id'], unique=True)
    op.create_index(op.f('ix_invoice_business_entities_uid'), 'invoice_business_entities', ['uid'], unique=True)
    op.create_table('meta_business_entities',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_business_entity', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_values_meta_ref_business_entity', 'meta_business_entities', ['key', 'ref_business_entity'], unique=True)
    op.create_index(op.f('ix_meta_business_entities_id'), 'meta_business_entities', ['id'], unique=True)
    op.create_index(op.f('ix_meta_business_entities_uid'), 'meta_business_entities', ['uid'], unique=True)
    op.create_table('meta_invoices',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_invoice', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_meta_invoices_key_ref', 'meta_invoices', ['key', 'ref_invoice'], unique=True)
    op.create_index(op.f('ix_meta_invoices_id'), 'meta_invoices', ['id'], unique=True)
    op.create_index(op.f('ix_meta_invoices_uid'), 'meta_invoices', ['uid'], unique=True)
    op.create_table('meta_permissions',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_permission', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_permission'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_meta_permissions_key_ref_permission', 'meta_permissions', ['key', 'ref_permission'], unique=True)
    op.create_index(op.f('ix_meta_permissions_id'), 'meta_permissions', ['id'], unique=True)
    op.create_index(op.f('ix_meta_permissions_uid'), 'meta_permissions', ['uid'], unique=True)
    op.create_table('meta_values',
    sa.Column('ref_value', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_value'], ['values.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_values_meta_key_ref_value', 'meta_values', ['key', 'ref_value'], unique=True)
    op.create_index(op.f('ix_meta_values_id'), 'meta_values', ['id'], unique=True)
    op.create_index(op.f('ix_meta_values_uid'), 'meta_values', ['uid'], unique=True)
    op.create_table('persons',
    sa.Column('first_names', sa.String(length=100), nullable=False),
    sa.Column('last_names', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('type_identifier', sa.String(length=50), nullable=True),
    sa.Column('ref_business_entity', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=True)
    op.create_index(op.f('ix_persons_uid'), 'persons', ['uid'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=True)
    op.create_index(op.f('ix_role_permissions_uid'), 'role_permissions', ['uid'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role_ref', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('otp_secret', sa.String(), nullable=True),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_ref'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english', username || ' ' || email || ' ' || full_name)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index('ix_users_role_ref_active', 'users', ['role_ref'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_table('values_hierarchy',
    sa.Column('ref_value_top', sa.Integer(), nullable=False),
    sa.Column('ref_value_bottom', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_value_bottom'], ['values.id'], ),
    sa.ForeignKeyConstraint(['ref_value_top'], ['values.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_values_hierarchy_id'), 'values_hierarchy', ['id'], unique=True)
    op.create_index(op.f('ix_values_hierarchy_uid'), 'values_hierarchy', ['uid'], unique=True)
    op.create_table('balances_business_entities',
    sa.Column('ref_business_entity', sa.Integer(), nullable=False),
    sa.Column('ref_balance', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_balance'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_balances_business_entities_id'), 'balances_business_entities', ['id'], unique=True)
    op.create_index(op.f('ix_balances_business_entities_uid'), 'balances_business_entities', ['uid'], unique=True)
    op.create_table('comparation_values_historical',
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('quantity_from', sa.Integer(), nullable=False),
    sa.Column('quantity_to', sa.Float(), nullable=False),
    sa.Column('value_from', sa.Integer(), nullable=False),
    sa.Column('value_to', sa.Integer(), nullable=False),
    sa.Column('original_comparison_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['original_comparison_id'], ['comparation_values.id'], ),
    sa.ForeignKeyConstraint(['value_from'], ['values.id'], ),
    sa.ForeignKeyConstraint(['value_to'], ['values.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_comparation_values_historical_id'), 'comparation_values_historical', ['id'], unique=True)
    op.create_index(op.f('ix_comparation_values_historical_uid'), 'comparation_values_historical', ['uid'], unique=True)
    op.create_table('meta_comparison_values',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_comparison_value', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_comparison_value'], ['comparation_values.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_values_meta_ref_comparison_value', 'meta_comparison_values', ['key', 'ref_comparison_value'], unique=True)
    op.create_index(op.f('ix_meta_comparison_values_id'), 'meta_comparison_values', ['id'], unique=True)
    op.create_index(op.f('ix_meta_comparison_values_uid'), 'meta_comparison_values', ['uid'], unique=True)
    op.create_table('meta_persons',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_person', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_person'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_values_meta_ref_person', 'meta_persons', ['key', 'ref_person'], unique=True)
    op.create_index(op.f('ix_meta_persons_id'), 'meta_persons', ['id'], unique=True)
    op.create_index(op.f('ix_meta_persons_uid'), 'meta_persons', ['uid'], unique=True)
    op.create_table('meta_users',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_user', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_meta_users_key_ref_user', 'meta_users', ['key', 'ref_user'], unique=True)
    op.create_index(op.f('ix_meta_users_id'), 'meta_users', ['id'], unique=True)
    op.create_index(op.f('ix_meta_users_uid'), 'meta_users', ['uid'], unique=True)
    op.create_table('transactions',
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('operation_type', sa.Enum('+', '-', name='operation_type_enum'), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('quantity_to', sa.String(), nullable=True),
    sa.Column('ref_by_user', sa.Integer(), nullable=False),
    sa.Column('ref_balance_from', sa.Integer(), nullable=False),
    sa.Column('ref_balance_to', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_balance_from'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['ref_balance_to'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['ref_by_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=True)
    op.create_index('ix_transactions_ref_balance_from_active', 'transactions', ['ref_balance_from'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_ref_balance_to_active', 'transactions', ['ref_balance_to'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_ref_by_user_active', 'transactions', ['ref_by_user'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_reference_code_active', 'transactions', ['reference_code'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_transactions_uid'), 'transactions', ['uid'], unique=True)
    op.create_index('uq_transactions_id', 'transactions', ['id'], unique=True)
    op.create_table('transactions_buffer',
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('operation_type', sa.Enum('+', '-', name='buffer_operation_type_enum'), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('trigger', sa.String(length=100), nullable=True),
    sa.Column('ref_inverse_transaction', sa.Integer(), nullable=False),
    sa.Column('ref_by_user', sa.Integer(), nullable=False),
    sa.Column('ref_balance_from', sa.Integer(), nullable=False),
    sa.Column('ref_balance_to', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_balance_from'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['ref_balance_to'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['ref_by_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ref_inverse_transaction'], ['transactions_buffer.id'], name='fk_transactions_buffer_inverse', use_alter=True),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_transactions_buffer_id'), 'transactions_buffer', ['id'], unique=True)
    op.create_index('ix_transactions_buffer_ref_balance_from_active', 'transactions_buffer', ['ref_balance_from'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_buffer_ref_balance_to_active', 'transactions_buffer', ['ref_balance_to'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_buffer_ref_by_user_active', 'transactions_buffer', ['ref_by_user'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_transactions_buffer_state_active', 'transactions_buffer', ['state'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_transactions_buffer_uid'), 'transactions_buffer', ['uid'], unique=True)
    op.create_index('uq_transactions_buffer_id', 'transactions_buffer', ['id'], unique=True)
    op.create_table('invoice_transactions',
    sa.Column('ref_invoice', sa.Integer(), nullable=False),
    sa.Column('ref_transaction', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['ref_transaction'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index(op.f('ix_invoice_transactions_id'), 'invoice_transactions', ['id'], unique=True)
    op.create_index(op.f('ix_invoice_transactions_uid'), 'invoice_transactions', ['uid'], unique=True)
    op.create_table('meta_comparison_values_historical',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_comparison_value_historical', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_comparison_value_historical'], ['comparation_values_historical.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_meta_comp_val_hist_ref_comp_val_hist', 'meta_comparison_values_historical', ['key', 'ref_comparison_value_historical'], unique=True)
    op.create_index(op.f('ix_meta_comparison_values_historical_id'), 'meta_comparison_values_historical', ['id'], unique=True)
    op.create_index(op.f('ix_meta_comparison_values_historical_uid'), 'meta_comparison_values_historical', ['uid'], unique=True)
    op.create_table('meta_transactions',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_transaction', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_transaction'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_values_meta_key_ref_transaction', 'meta_transactions', ['key', 'ref_transaction'], unique=True)
    op.create_index(op.f('ix_meta_transactions_id'), 'meta_transactions', ['id'], unique=True)
    op.create_index(op.f('ix_meta_transactions_uid'), 'meta_transactions', ['uid'], unique=True)
    op.create_table('meta_transactions_buffer',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ref_transaction_buffer', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_transaction_buffer'], ['transactions_buffer.id'], ),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_index('idx_meta_tx_buffer_key_ref', 'meta_transactions_buffer', ['key', 'ref_transaction_buffer'], unique=True)
    op.create_index(op.f('ix_meta_transactions_buffer_id'), 'meta_transactions_buffer', ['id'], unique=True)
    op.create_index(op.f('ix_meta_transactions_buffer_uid'), 'meta_transactions_buffer', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_transactions_buffer_uid'), table_name='meta_transactions_buffer')
    op.drop_index(op.f('ix_meta_transactions_buffer_id'), table_name='meta_transactions_buffer')
    op.drop_index('idx_meta_tx_buffer_key_ref', table_name='meta_transactions_buffer')
    op.drop_table('meta_transactions_buffer')
    op.drop_index(op.f('ix_meta_transactions_uid'), table_name='meta_transactions')
    op.drop_index(op.f('ix_meta_transactions_id'), table_name='meta_transactions')
    op.drop_index('idx_values_meta_key_ref_transaction', table_name='meta_transactions')
    op.drop_table('meta_transactions')
    op.drop_index(op.f('ix_meta_comparison_values_historical_uid'), table_name='meta_comparison_values_historical')
    op.drop_index(op.f('ix_meta_comparison_values_historical_id'), table_name='meta_comparison_values_historical')
    op.drop_index('idx_meta_comp_val_hist_ref_comp_val_hist', table_name='meta_comparison_values_historical')
    op.drop_table('meta_comparison_values_historical')
    op.drop_index(op.f('ix_invoice_transactions_uid'), table_name='invoice_transactions')
    op.drop_index(op.f('ix_invoice_transactions_id'), table_name='invoice_transactions')
    op.drop_table('invoice_transactions')
    op.drop_index('uq_transactions_buffer_id', table_name='transactions_buffer')
    op.drop_index(op.f('ix_transactions_buffer_uid'), table_name='transactions_buffer')
    op.drop_index('ix_transactions_buffer_state_active', table_name='transactions_buffer', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_buffer_ref_by_user_active', table_name='transactions_buffer', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_buffer_ref_balance_to_active', table_name='transactions_buffer', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_buffer_ref_balance_from_active', table_name='transactions_buffer', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_transactions_buffer_id'), table_name='transactions_buffer')
    op.drop_table('transactions_buffer')
    op.drop_index('uq_transactions_id', table_name='transactions')
    op.drop_index(op.f('ix_transactions_uid'), table_name='transactions')
    op.drop_index('ix_transactions_reference_code_active', table_name='transactions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_ref_by_user_active', table_name='transactions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_ref_balance_to_active', table_name='transactions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_transactions_ref_balance_from_active', table_name='transactions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_meta_users_uid'), table_name='meta_users')
    op.drop_index(op.f('ix_meta_users_id'), table_name='meta_users')
    op.drop_index('idx_meta_users_key_ref_user', table_name='meta_users')
    op.drop_table('meta_users')
    op.drop_index(op.f('ix_meta_persons_uid'), table_name='meta_persons')
    op.drop_index(op.f('ix_meta_persons_id'), table_name='meta_persons')
    op.drop_index('idx_values_meta_ref_person', table_name='meta_persons')
    op.drop_table('meta_persons')
    op.drop_index(op.f('ix_meta_comparison_values_uid'), table_name='meta_comparison_values')
    op.drop_index(op.f('ix_meta_comparison_values_id'), table_name='meta_comparison_values')
    op.drop_index('idx_values_meta_ref_comparison_value', table_name='meta_comparison_values')
    op.drop_table('meta_comparison_values')
    op.drop_index(op.f('ix_comparation_values_historical_uid'), table_name='comparation_values_historical')
    op.drop_index(op.f('ix_comparation_values_historical_id'), table_name='comparation_values_historical')
    op.drop_table('comparation_values_historical')
    op.drop_index(op.f('ix_balances_business_entities_uid'), table_name='balances_business_entities')
    op.drop_index(op.f('ix_balances_business_entities_id'), table_name='balances_business_entities')
    op.drop_table('balances_business_entities')
    op.drop_index(op.f('ix_values_hierarchy_uid'), table_name='values_hierarchy')
    op.drop_index(op.f('ix_values_hierarchy_id'), table_name='values_hierarchy')
    op.drop_table('values_hierarchy')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index('ix_users_role_ref_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_uid'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_persons_uid'), table_name='persons')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_meta_values_uid'), table_name='meta_values')
    op.drop_index(op.f('ix_meta_values_id'), table_name='meta_values')
    op.drop_index('idx_values_meta_key_ref_value', table_name='meta_values')
    op.drop_table('meta_values')
    op.drop_index(op.f('ix_meta_permissions_uid'), table_name='meta_permissions')
    op.drop_index(op.f('ix_meta_permissions_id'), table_name='meta_permissions')
    op.drop_index('idx_meta_permissions_key_ref_permission', table_name='meta_permissions')
    op.drop_table('meta_permissions')
    op.drop_index(op.f('ix_meta_invoices_uid'), table_name='meta_invoices')
    op.drop_index(op.f('ix_meta_invoices_id'), table_name='meta_invoices')
    op.drop_index('idx_meta_invoices_key_ref', table_name='meta_invoices')
    op.drop_table('meta_invoices')
    op.drop_index(op.f('ix_meta_business_entities_uid'), table_name='meta_business_entities')
    op.drop_index(op.f('ix_meta_business_entities_id'), table_name='meta_business_entities')
    op.drop_index('idx_values_meta_ref_business_entity', table_name='meta_business_entities')
    op.drop_table('meta_business_entities')
    op.drop_index(op.f('ix_invoice_business_entities_uid'), table_name='invoice_business_entities')
    op.drop_index(op.f('ix_invoice_business_entities_id'), table_name='invoice_business_entities')
    op.drop_table('invoice_business_entities')
    op.drop_index('ix_comparison_values_value_to_context', table_name='comparation_values')
    op.drop_index('ix_comparison_values_value_from_context', table_name='comparation_values')
    op.drop_index('ix_comparation_values_value_to_active', table_name='comparation_values', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_comparation_values_value_from_active', table_name='comparation_values', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_comparation_values_uid'), table_name='comparation_values')
    op.drop_index(op.f('ix_comparation_values_id'), table_name='comparation_values')
    op.drop_index('ix_comparation_values_context_active', table_name='comparation_values')
    op.drop_table('comparation_values')
    op.drop_index(op.f('ix_business_entities_hierarchy_uid'), table_name='business_entities_hierarchy')
    op.drop_index(op.f('ix_business_entities_hierarchy_id'), table_name='business_entities_hierarchy')
    op.drop_table('business_entities_hierarchy')
    op.drop_index(op.f('ix_business_entities_groups_connections_uid'), table_name='business_entities_groups_connections')
    op.drop_index(op.f('ix_business_entities_groups_connections_id'), table_name='business_entities_groups_connections')
    op.drop_table('business_entities_groups_connections')
    op.drop_index(op.f('ix_balances_uid'), table_name='balances')
    op.drop_index('ix_balances_type_active', table_name='balances', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_balances_ref_value_active', table_name='balances', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_balances_id'), table_name='balances')
    op.drop_table('balances')
    op.drop_index(op.f('ix_values_uid'), table_name='values')
    op.drop_index('ix_values_name_type', table_name='values')
    op.drop_index('ix_values_name_context_type', table_name='values')
    op.drop_index('ix_values_name_context', table_name='values')
    op.drop_index(op.f('ix_values_id'), table_name='values')
    op.drop_index('ix_values_context_active', table_name='values')
    op.drop_table('values')
    op.drop_index(op.f('ix_roles_uid'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_uid'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_options_uid'), table_name='options')
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_index('idx_options_name', table_name='options')
    op.drop_index('idx_options_context', table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_invoices_uid'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_image_files_uid'), table_name='image_files')
    op.drop_index(op.f('ix_image_files_id'), table_name='image_files')
    op.drop_table('image_files')
    op.drop_index(op.f('ix_business_entities_groups_uid'), table_name='business_entities_groups')
    op.drop_index(op.f('ix_business_entities_groups_id'), table_name='business_entities_groups')
    op.drop_table('business_entities_groups')
    op.drop_index(op.f('ix_business_entities_uid'), table_name='business_entities')
    op.drop_index(op.f('ix_business_entities_id'), table_name='business_entities')
    op.drop_table('business_entities')
    # ### end Alembic commands ###
