"""Sync models with DBML (Pivot & Meta refactor)

Revision ID: 78e7a0e4063a
Revises: 953db610c518
Create Date: 2026-05-07 19:05:01.719331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78e7a0e4063a'
down_revision: Union[str, None] = '953db610c518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_invoice_business_entities_active', table_name='invoice_business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_invoice_business_entities_id', table_name='invoice_business_entities')
    op.drop_index('ix_invoice_business_entities_uid', table_name='invoice_business_entities')
    op.drop_table('invoice_business_entities')
    op.drop_index('idx_role_permissions_active', table_name='role_permissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_role_permissions_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_uid', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('idx_meta_business_entities_active', table_name='meta_business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_values_meta_ref_business_entity', table_name='meta_business_entities')
    op.drop_index('ix_meta_business_entities_id', table_name='meta_business_entities')
    op.drop_index('ix_meta_business_entities_uid', table_name='meta_business_entities')
    op.drop_table('meta_business_entities')
    op.drop_index('idx_meta_comparison_values_active', table_name='meta_comparison_values', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_values_meta_ref_comparison_value', table_name='meta_comparison_values')
    op.drop_index('ix_meta_comparison_values_id', table_name='meta_comparison_values')
    op.drop_index('ix_meta_comparison_values_uid', table_name='meta_comparison_values')
    op.drop_table('meta_comparison_values')
    op.drop_index('idx_meta_transactions_buffer_active', table_name='meta_transactions_buffer', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_tx_buffer_key_ref', table_name='meta_transactions_buffer')
    op.drop_index('ix_meta_transactions_buffer_id', table_name='meta_transactions_buffer')
    op.drop_index('ix_meta_transactions_buffer_uid', table_name='meta_transactions_buffer')
    op.drop_table('meta_transactions_buffer')
    op.drop_index('idx_meta_invoices_active', table_name='meta_invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_invoices_key_ref', table_name='meta_invoices')
    op.drop_index('ix_meta_invoices_id', table_name='meta_invoices')
    op.drop_index('ix_meta_invoices_uid', table_name='meta_invoices')
    op.drop_table('meta_invoices')
    op.drop_index('idx_invoice_transactions_active', table_name='invoice_transactions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_invoice_transactions_id', table_name='invoice_transactions')
    op.drop_index('ix_invoice_transactions_uid', table_name='invoice_transactions')
    op.drop_table('invoice_transactions')
    op.drop_index('idx_values_hierarchy_active', table_name='values_hierarchy', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_values_hierarchy_id', table_name='values_hierarchy')
    op.drop_index('ix_values_hierarchy_uid', table_name='values_hierarchy')
    op.drop_table('values_hierarchy')
    op.drop_index('idx_meta_transactions_active', table_name='meta_transactions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_values_meta_key_ref_transaction', table_name='meta_transactions')
    op.drop_index('ix_meta_transactions_id', table_name='meta_transactions')
    op.drop_index('ix_meta_transactions_uid', table_name='meta_transactions')
    op.drop_table('meta_transactions')
    op.drop_index('idx_balances_business_entities_active', table_name='balances_business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_balances_business_entities_id', table_name='balances_business_entities')
    op.drop_index('ix_balances_business_entities_uid', table_name='balances_business_entities')
    op.drop_table('balances_business_entities')
    op.drop_index('idx_meta_persons_active', table_name='meta_persons', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_values_meta_ref_person', table_name='meta_persons')
    op.drop_index('ix_meta_persons_id', table_name='meta_persons')
    op.drop_index('ix_meta_persons_uid', table_name='meta_persons')
    op.drop_table('meta_persons')
    op.drop_index('idx_meta_permissions_active', table_name='meta_permissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_permissions_key_ref_permission', table_name='meta_permissions')
    op.drop_index('ix_meta_permissions_id', table_name='meta_permissions')
    op.drop_index('ix_meta_permissions_uid', table_name='meta_permissions')
    op.drop_table('meta_permissions')
    op.drop_index('idx_meta_values_active', table_name='meta_values', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_values_meta_key_ref_value', table_name='meta_values')
    op.drop_index('ix_meta_values_id', table_name='meta_values')
    op.drop_index('ix_meta_values_uid', table_name='meta_values')
    op.drop_table('meta_values')
    op.drop_index('idx_meta_users_active', table_name='meta_users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_meta_users_key_ref_user', table_name='meta_users')
    op.drop_index('ix_meta_users_id', table_name='meta_users')
    op.drop_index('ix_meta_users_uid', table_name='meta_users')
    op.drop_table('meta_users')
    op.drop_index('idx_meta_comp_val_hist_ref_comp_val_hist', table_name='meta_comparison_values_historical')
    op.drop_index('idx_meta_comparison_values_historical_active', table_name='meta_comparison_values_historical', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_meta_comparison_values_historical_id', table_name='meta_comparison_values_historical')
    op.drop_index('ix_meta_comparison_values_historical_uid', table_name='meta_comparison_values_historical')
    op.drop_table('meta_comparison_values_historical')
    op.drop_index('idx_business_entities_hierarchy_active', table_name='business_entities_hierarchy', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_business_entities_hierarchy_id', table_name='business_entities_hierarchy')
    op.drop_index('ix_business_entities_hierarchy_uid', table_name='business_entities_hierarchy')
    op.drop_table('business_entities_hierarchy')
    op.alter_column('balances', 'type',
               existing_type=postgresql.ENUM('basic', 'adjustment', name='balance_type_enum'),
               type_=sa.Enum('basic', 'adjustment', name='balance_type_enum', native_enum=False),
               existing_nullable=False)
    op.drop_index('idx_balances_active', table_name='balances', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_active', table_name='business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_groups_active', table_name='business_entities_groups', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_groups_connections_active', table_name='business_entities_groups_connections', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_comparation_values_active', table_name='comparation_values', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_comparation_values_historical_active', table_name='comparation_values_historical', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_image_files_active', table_name='image_files', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_invoices_active', table_name='invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_options_active', table_name='options', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_permissions_active', table_name='permissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_persons_active', table_name='persons', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_roles_active', table_name='roles', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_transactions_active', table_name='transactions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_transactions_buffer_active', table_name='transactions_buffer', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_users_active', table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english', username || ' ' || email || ' ' || full_name)")], unique=False, postgresql_using='gin')
    op.drop_index('idx_values_active', table_name='values', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_values_active', 'values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english'::regconfig, (((username::text || ' '::text) || email::text) || ' '::text) || full_name::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_users_active', 'users', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_transactions_buffer_active', 'transactions_buffer', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_transactions_active', 'transactions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_roles_active', 'roles', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_persons_active', 'persons', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_permissions_active', 'permissions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_options_active', 'options', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_invoices_active', 'invoices', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_image_files_active', 'image_files', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_comparation_values_historical_active', 'comparation_values_historical', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_comparation_values_active', 'comparation_values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_groups_connections_active', 'business_entities_groups_connections', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_groups_active', 'business_entities_groups', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_active', 'business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_balances_active', 'balances', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('balances', 'type',
               existing_type=sa.Enum('basic', 'adjustment', name='balance_type_enum', native_enum=False),
               type_=postgresql.ENUM('basic', 'adjustment', name='balance_type_enum'),
               existing_nullable=False)
    op.create_table('business_entities_hierarchy',
    sa.Column('ref_entity_top', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ref_entity_bottom', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_entity_bottom'], ['business_entities.id'], name='business_entities_hierarchy_ref_entity_bottom_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_entity_top'], ['business_entities.id'], name='business_entities_hierarchy_ref_entity_top_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'id', name='business_entities_hierarchy_pkey')
    )
    op.create_index('ix_business_entities_hierarchy_uid', 'business_entities_hierarchy', ['uid'], unique=True)
    op.create_index('ix_business_entities_hierarchy_id', 'business_entities_hierarchy', ['id'], unique=True)
    op.create_index('idx_business_entities_hierarchy_active', 'business_entities_hierarchy', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_comparison_values_historical',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_comparison_value_historical', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_comparison_value_historical'], ['comparation_values_historical.id'], name='meta_comparison_values_histor_ref_comparison_value_histori_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_comparison_values_historical_pkey')
    )
    op.create_index('ix_meta_comparison_values_historical_uid', 'meta_comparison_values_historical', ['uid'], unique=True)
    op.create_index('ix_meta_comparison_values_historical_id', 'meta_comparison_values_historical', ['id'], unique=True)
    op.create_index('idx_meta_comparison_values_historical_active', 'meta_comparison_values_historical', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_meta_comp_val_hist_ref_comp_val_hist', 'meta_comparison_values_historical', ['key', 'ref_comparison_value_historical'], unique=True)
    op.create_table('meta_users',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_user'], ['users.id'], name='meta_users_ref_user_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_users_pkey')
    )
    op.create_index('ix_meta_users_uid', 'meta_users', ['uid'], unique=True)
    op.create_index('ix_meta_users_id', 'meta_users', ['id'], unique=True)
    op.create_index('idx_meta_users_key_ref_user', 'meta_users', ['key', 'ref_user'], unique=True)
    op.create_index('idx_meta_users_active', 'meta_users', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_values',
    sa.Column('ref_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_value'], ['values.id'], name='meta_values_ref_value_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_values_pkey')
    )
    op.create_index('ix_meta_values_uid', 'meta_values', ['uid'], unique=True)
    op.create_index('ix_meta_values_id', 'meta_values', ['id'], unique=True)
    op.create_index('idx_values_meta_key_ref_value', 'meta_values', ['key', 'ref_value'], unique=True)
    op.create_index('idx_meta_values_active', 'meta_values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_permissions',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_permission', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_permission'], ['permissions.id'], name='meta_permissions_ref_permission_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_permissions_pkey')
    )
    op.create_index('ix_meta_permissions_uid', 'meta_permissions', ['uid'], unique=True)
    op.create_index('ix_meta_permissions_id', 'meta_permissions', ['id'], unique=True)
    op.create_index('idx_meta_permissions_key_ref_permission', 'meta_permissions', ['key', 'ref_permission'], unique=True)
    op.create_index('idx_meta_permissions_active', 'meta_permissions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_persons',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_person', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_person'], ['persons.id'], name='meta_persons_ref_person_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_persons_pkey')
    )
    op.create_index('ix_meta_persons_uid', 'meta_persons', ['uid'], unique=True)
    op.create_index('ix_meta_persons_id', 'meta_persons', ['id'], unique=True)
    op.create_index('idx_values_meta_ref_person', 'meta_persons', ['key', 'ref_person'], unique=True)
    op.create_index('idx_meta_persons_active', 'meta_persons', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('balances_business_entities',
    sa.Column('ref_business_entity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ref_balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_balance'], ['balances.id'], name='balances_business_entities_ref_balance_fkey'),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], name='balances_business_entities_ref_business_entity_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'id', name='balances_business_entities_pkey')
    )
    op.create_index('ix_balances_business_entities_uid', 'balances_business_entities', ['uid'], unique=True)
    op.create_index('ix_balances_business_entities_id', 'balances_business_entities', ['id'], unique=True)
    op.create_index('idx_balances_business_entities_active', 'balances_business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_transactions',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_transaction', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_transaction'], ['transactions.id'], name='meta_transactions_ref_transaction_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_transactions_pkey')
    )
    op.create_index('ix_meta_transactions_uid', 'meta_transactions', ['uid'], unique=True)
    op.create_index('ix_meta_transactions_id', 'meta_transactions', ['id'], unique=True)
    op.create_index('idx_values_meta_key_ref_transaction', 'meta_transactions', ['key', 'ref_transaction'], unique=True)
    op.create_index('idx_meta_transactions_active', 'meta_transactions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('values_hierarchy',
    sa.Column('ref_value_top', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ref_value_bottom', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_value_bottom'], ['values.id'], name='values_hierarchy_ref_value_bottom_fkey'),
    sa.ForeignKeyConstraint(['ref_value_top'], ['values.id'], name='values_hierarchy_ref_value_top_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='values_hierarchy_pkey')
    )
    op.create_index('ix_values_hierarchy_uid', 'values_hierarchy', ['uid'], unique=True)
    op.create_index('ix_values_hierarchy_id', 'values_hierarchy', ['id'], unique=True)
    op.create_index('idx_values_hierarchy_active', 'values_hierarchy', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('invoice_transactions',
    sa.Column('ref_invoice', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ref_transaction', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], name='invoice_transactions_ref_invoice_fkey'),
    sa.ForeignKeyConstraint(['ref_transaction'], ['transactions.id'], name='invoice_transactions_ref_transaction_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='invoice_transactions_pkey')
    )
    op.create_index('ix_invoice_transactions_uid', 'invoice_transactions', ['uid'], unique=True)
    op.create_index('ix_invoice_transactions_id', 'invoice_transactions', ['id'], unique=True)
    op.create_index('idx_invoice_transactions_active', 'invoice_transactions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_invoices',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_invoice', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], name='meta_invoices_ref_invoice_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_invoices_pkey')
    )
    op.create_index('ix_meta_invoices_uid', 'meta_invoices', ['uid'], unique=True)
    op.create_index('ix_meta_invoices_id', 'meta_invoices', ['id'], unique=True)
    op.create_index('idx_meta_invoices_key_ref', 'meta_invoices', ['key', 'ref_invoice'], unique=True)
    op.create_index('idx_meta_invoices_active', 'meta_invoices', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_transactions_buffer',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_transaction_buffer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_transaction_buffer'], ['transactions_buffer.id'], name='meta_transactions_buffer_ref_transaction_buffer_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_transactions_buffer_pkey')
    )
    op.create_index('ix_meta_transactions_buffer_uid', 'meta_transactions_buffer', ['uid'], unique=True)
    op.create_index('ix_meta_transactions_buffer_id', 'meta_transactions_buffer', ['id'], unique=True)
    op.create_index('idx_meta_tx_buffer_key_ref', 'meta_transactions_buffer', ['key', 'ref_transaction_buffer'], unique=True)
    op.create_index('idx_meta_transactions_buffer_active', 'meta_transactions_buffer', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_comparison_values',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_comparison_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_comparison_value'], ['comparation_values.id'], name='meta_comparison_values_ref_comparison_value_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_comparison_values_pkey')
    )
    op.create_index('ix_meta_comparison_values_uid', 'meta_comparison_values', ['uid'], unique=True)
    op.create_index('ix_meta_comparison_values_id', 'meta_comparison_values', ['id'], unique=True)
    op.create_index('idx_values_meta_ref_comparison_value', 'meta_comparison_values', ['key', 'ref_comparison_value'], unique=True)
    op.create_index('idx_meta_comparison_values_active', 'meta_comparison_values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('meta_business_entities',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_business_entity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], name='meta_business_entities_ref_business_entity_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'id', name='meta_business_entities_pkey')
    )
    op.create_index('ix_meta_business_entities_uid', 'meta_business_entities', ['uid'], unique=True)
    op.create_index('ix_meta_business_entities_id', 'meta_business_entities', ['id'], unique=True)
    op.create_index('idx_values_meta_ref_business_entity', 'meta_business_entities', ['key', 'ref_business_entity'], unique=True)
    op.create_index('idx_meta_business_entities_active', 'meta_business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_permission_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_permissions_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'id', name='role_permissions_pkey')
    )
    op.create_index('ix_role_permissions_uid', 'role_permissions', ['uid'], unique=True)
    op.create_index('ix_role_permissions_id', 'role_permissions', ['id'], unique=True)
    op.create_index('idx_role_permissions_active', 'role_permissions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('invoice_business_entities',
    sa.Column('ref_invoice', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ref_business_entity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_business_entity'], ['business_entities.id'], name='invoice_business_entities_ref_business_entity_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_invoice'], ['invoices.id'], name='invoice_business_entities_ref_invoice_fkey'),
    sa.PrimaryKeyConstraint('uid', 'id', name='invoice_business_entities_pkey')
    )
    op.create_index('ix_invoice_business_entities_uid', 'invoice_business_entities', ['uid'], unique=True)
    op.create_index('ix_invoice_business_entities_id', 'invoice_business_entities', ['id'], unique=True)
    op.create_index('idx_invoice_business_entities_active', 'invoice_business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
