"""Add decorators_balances and is_reactive

Revision ID: b5f528968f67
Revises: d69683ffa8e6
Create Date: 2026-05-15 19:04:12.667833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f528968f67'
down_revision: Union[str, None] = 'd69683ffa8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decorators_balances',
    sa.Column('ref_balance_from', sa.Integer(), nullable=False),
    sa.Column('ref_balance_to', sa.Integer(), nullable=False),
    sa.Column('balance_decorators', sa.JSON(), nullable=True),
    sa.Column('is_reactive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_balance_from'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['ref_balance_to'], ['balances.id'], ),
    sa.PrimaryKeyConstraint('ref_balance_from', 'ref_balance_to')
    )
    op.drop_index('idx_balances_active', table_name='balances', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_active', table_name='business_entities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_business_entities_groups_active', table_name='business_entities_groups', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_comparation_values_active', table_name='comparation_values', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_comparation_values_historical_active', table_name='comparation_values_historical', postgresql_where='(deleted_at IS NULL)')
    op.add_column('decorators_comparation_values', sa.Column('is_reactive', sa.Boolean(), nullable=False))
    op.add_column('decorators_comparation_values_historical', sa.Column('is_reactive', sa.Boolean(), nullable=False))
    op.drop_index('idx_image_files_active', table_name='image_files', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_invoices_active', table_name='invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_options_active', table_name='options', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_permissions_active', table_name='permissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_persons_active', table_name='persons', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_roles_active', table_name='roles', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_transactions_active', table_name='transactions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_transactions_buffer_active', table_name='transactions_buffer', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_users_active', table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english', username || ' ' || email || ' ' || full_name)")], unique=False, postgresql_using='gin')
    op.drop_index('idx_values_active', table_name='values', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_values_active', 'values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.text("to_tsvector('english'::regconfig, (((username::text || ' '::text) || email::text) || ' '::text) || full_name::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_users_active', 'users', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_transactions_buffer_active', 'transactions_buffer', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_transactions_active', 'transactions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_roles_active', 'roles', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_persons_active', 'persons', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_permissions_active', 'permissions', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_options_active', 'options', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_invoices_active', 'invoices', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_image_files_active', 'image_files', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('decorators_comparation_values_historical', 'is_reactive')
    op.drop_column('decorators_comparation_values', 'is_reactive')
    op.create_index('idx_comparation_values_historical_active', 'comparation_values_historical', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_comparation_values_active', 'comparation_values', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_groups_active', 'business_entities_groups', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_business_entities_active', 'business_entities', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_balances_active', 'balances', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_table('decorators_balances')
    # ### end Alembic commands ###
