"""Add comparison value decorators tables

Revision ID: d69683ffa8e6
Revises: 15a28bdc8b2e
Create Date: 2026-05-07 19:33:51.942147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69683ffa8e6'
down_revision: Union[str, None] = '15a28bdc8b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decorators_comparation_values',
    sa.Column('ref_comparation_values_from', sa.Integer(), nullable=False),
    sa.Column('ref_comparation_values_to', sa.Integer(), nullable=False),
    sa.Column('comparison_decorators', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ref_comparation_values_from'], ['comparation_values.id'], ),
    sa.ForeignKeyConstraint(['ref_comparation_values_to'], ['comparation_values.id'], ),
    sa.PrimaryKeyConstraint('ref_comparation_values_from', 'ref_comparation_values_to')
    )
    op.create_table('decorators_comparation_values_historical',
    sa.Column('ref_comparation_values_from', sa.Integer(), nullable=False),
    sa.Column('ref_comparation_values_to', sa.Integer(), nullable=False),
    sa.Column('comparison_decorators', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ref_comparation_values_from'], ['comparation_values_historical.id'], ),
    sa.ForeignKeyConstraint(['ref_comparation_values_to'], ['comparation_values_historical.id'], ),
    sa.PrimaryKeyConstraint('ref_comparation_values_from', 'ref_comparation_values_to')
    )
    # Removed redundant dynamic index drops
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed redundant dynamic index recreations
    pass
    op.drop_table('decorators_comparation_values_historical')
    op.drop_table('decorators_comparation_values')
    # ### end Alembic commands ###
